# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"bulba_url_for": "01_scraper.ipynb",
         "sanitize_name": "01_scraper.ipynb",
         "fetch_page_soup": "01_scraper.ipynb",
         "save_card_list": "01_scraper.ipynb",
         "load_card_list": "01_scraper.ipynb",
         "fetch_card_list": "01_scraper.ipynb",
         "dedupe_image_urls": "01_scraper.ipynb",
         "extract_image_urls": "01_scraper.ipynb",
         "IMG_EXCEPTIONS": "01_scraper.ipynb",
         "isTrainerCard": "01_scraper.ipynb",
         "extract_pokemon_card_text": "01_scraper.ipynb",
         "extract_trainer_card_text": "01_scraper.ipynb",
         "extract_card_text": "01_scraper.ipynb",
         "get_card_numbers": "01_scraper.ipynb",
         "update_card_details": "01_scraper.ipynb",
         "fetch_image": "01_scraper.ipynb",
         "save_image": "01_scraper.ipynb",
         "fetch_images_for_cards": "01_scraper.ipynb",
         "PROJ_HOME": "01_scraper.ipynb",
         "fetch_card_img_s3": "01_scraper.ipynb",
         "augment_brightness": "02_augmentation.ipynb",
         "transform_image": "02_augmentation.ipynb",
         "fetch_background_images": "02_augmentation.ipynb",
         "BKG_SRC": "02_augmentation.ipynb",
         "apply_random_background": "02_augmentation.ipynb",
         "img_s3keys": "02_augmentation.ipynb",
         "augment_card_and_save": "02_augmentation.ipynb",
         "ON_JUPY": "WebService.ipynb",
         "static_dir": "WebService.ipynb",
         "templates": "WebService.ipynb",
         "static_files": "WebService.ipynb",
         "data_files": "WebService.ipynb",
         "learn": "WebService.ipynb",
         "home": "WebService.ipynb",
         "card": "WebService.ipynb",
         "feedback": "WebService.ipynb",
         "analyze": "WebService.ipynb",
         "routes": "WebService.ipynb",
         "app": "WebService.ipynb"}

modules = ["scraper.py",
           "imgaug.py",
           "webservice.py"]

doc_url = "https://wooduk.github.io/pokedexr/"

git_url = "https://github.com/wooduk/pokedexr/tree/master/"

def custom_doc_links(name): return None
