# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fetch_links": "01_scraper.ipynb",
         "SCHEME": "01_scraper.ipynb",
         "BULB_BASE_URL": "01_scraper.ipynb",
         "get_camel_name": "01_scraper.ipynb",
         "get_image_urls": "01_scraper.ipynb",
         "IMG_EXCEPTIONS": "01_scraper.ipynb",
         "fetch_image": "01_scraper.ipynb",
         "store_image": "01_scraper.ipynb",
         "push_image_to_s3": "01_scraper.ipynb",
         "save_image_local": "01_scraper.ipynb",
         "BUCKET_NAME": "01_scraper.ipynb",
         "LOCAL_FOLDER": "01_scraper.ipynb",
         "main": "01_scraper.ipynb",
         "augment_brightness_camera_images": "02_augmentation.ipynb",
         "transform_image": "02_augmentation.ipynb",
         "fetch_background_images": "02_augmentation.ipynb",
         "BKG_SRC": "02_augmentation.ipynb",
         "apply_random_background": "02_augmentation.ipynb"}

modules = ["scraper.py",
           "augmentation.py"]

doc_url = "https://wooduk.github.io/pokedexr/"

git_url = "https://github.com/wooduk/pokedexr/tree/master/"

def custom_doc_links(name): return None
