# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BASE_URL": "00_core.ipynb",
         "get_camel_name": "00_core.ipynb",
         "get_image_from_page": "00_core.ipynb",
         "IMG_EXCEPTIONS": "00_core.ipynb",
         "augment_brightness_camera_images": "00_core.ipynb",
         "transform_image": "00_core.ipynb",
         "fetch_background_images": "00_core.ipynb",
         "BKG_SRC": "00_core.ipynb",
         "apply_random_background": "00_core.ipynb",
         "wr": "00_core.ipynb",
         "push_images_to_s3": "00_core.ipynb"}

modules = ["bulbascraper.py"]

doc_url = "https://wooduk.github.io/bulbascraper/"

git_url = "https://github.com/wooduk/bulbascraper/tree/master/"

def custom_doc_links(name): return None
